### ISSUE TITLE
ログインするには確認コードが必要です

### ISSUE THREAD

**Issue by fallingleaflun** [Saccubus/Saccubus1#75]
ログインできません

**Comment by nnn-revo2012** [comment]
The login function of Saccubus does not support two-factor authentication(2FA).
Please cancel the 2FA or log in with Firefox and check browser sharing.

**Comment by fallingleaflun** [comment]
Thank you very much!

> The login function of Saccubus does not support two-factor authentication(2FA). Please cancel the 2FA or log in with Firefox and check browser sharing ![sac109](https://user-images.githubusercontent.com/45882358/166112851-9891d331-977e-464d-bca6-579fc1ed172b.png) .
