### ISSUE TITLE
コメントの日時での制限について

### ISSUE THREAD

**Issue by skasdfyu** [Saccubus/Saccubus1#76]
質問失礼します。
昔の動画ですと最近のコメントによるネタバレが多く楽しさが落ちてしまいます。なので普段昔の動画を見るときは、コメント表示を動画投稿から30日程度に抑えることがよくあります。しかし、さきゅばすではWIKIを見ても日時による制限について言及している項目はありません。何か設定方法があれば教えてほしいです。

**Comment by nnn-revo2012** [comment]
メイン画面の「URL/ID」の下の「過去ログ」のところに日付を 2023/05/01 19:00 のように指定するとその時点でのコメントを取得できると思います。Wikiかドキュメントのどれかに書いてあったかと思います。

**Comment by skasdfyu** [comment]
過去ログに2009/7/7 7:7:7 や 2009/7/7 7:7 や 2009/7/7 のように入力してみても、投稿者コメントのダウンロード開始中で終了してしまいます。

**Comment by nnn-revo2012** [comment]
>>過去ログに2009/7/7 7:7:7 や 2009/7/7 7:7 や 2009/7/7 のように入力してみても、投稿者コメントのダウンロード開始中で終了してしまいます。

日付変換でエラーになっているみたいです。調査して修正しておきます。

**Comment by nnn-revo2012** [comment]
修正しました。
https://github.com/Saccubus/Saccubus1/releases/tag/1.70.0.10a
https://github.com/Saccubus/Saccubus1/releases/tag/1.67.8.17a

- 過去ログ日付指定時に変換エラーで終了するのを修正
  (1.70.0.05/1.67.8.12以降発生)
